version: "3"

services:
  duckrails:
    build:
      context: .
    ports:
      - 8080:80
    environment:
      DATABASE_ADAPTER: sqlite3
      DATABASE_NAME: db/sqlite/production.sqlite3
      SECRET_KEY_BASE: "61867f2ea52bfcd0956063c8947abd745968b9830387aba3034c3bfd2c63d2e22519d0b14df362f85bacd3d36029139a2e5ccb0a08bd2bd88f7ef353556dd7fa"
    restart: on-failure
    volumes:
      - ./db/sqlite/:/opt/duckrails/db/sqlite/
