version: "3"

services:
  duckrails:
    build:
      context: .
    ports:
      - 8080:80
    environment:
      DATABASE_ADAPTER: postgresql
      DATABASE_PORT: 5432
      DATABASE_NAME: duckrails
      DATABASE_HOSTNAME: postgres
      DATABASE_PASSWORD: p4ssw0rd
      DATABASE_USERNAME: postgres
      SECRET_KEY_BASE: "61867f2ea52bfcd0956063c8947abd745968b9830387aba3034c3bfd2c63d2e22519d0b14df362f85bacd3d36029139a2e5ccb0a08bd2bd88f7ef353556dd7fa"
    restart: on-failure
    depends_on:
      - postgres
  postgres:
    image: postgres:10
    environment:
      POSTGRES_DB: duckrails 
      POSTGRES_PASSWORD: p4ssw0rd
      POSTGRES_USERNAME: postgres
 
