# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: unicode
  database: db/development
  pool: 5
  username: nithin
  password: nithin
  timeout: 5000


test:
  adapter: postgresql
  encoding: unicode
  database: db/test
  pool: 5
  username: nithin
  password: nithin
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: db/test
  pool: 5
  username: nithin
  password: nithin
  timeout: 5000
